version: '3'
services:
  api:
    build: .
    environment:
      - DB_NAME=testing
      - TEST_DB_NAME=realtesting
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - NODE_ENV=development
      - PORT=8000
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:14.9
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"

volumes:
  postgres_data: